/* Copyright 2019 NEC Corporation

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at
 
     http://www.apache.org/licenses/LICENSE-2.0
 
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

*/
package ;
import java.util.List;
import java.util.ArrayList;
import java.lang.String;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OaseActionUtility implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    private java.util.List<java.lang.String> id = new ArrayList<>();
    private java.util.List<java.lang.String> parameterInfo = new ArrayList<>();
    private java.util.List<java.lang.String> retryCount = new ArrayList<>();
    private java.util.List<java.lang.String> retryInterval = new ArrayList<>();
    private java.util.List<java.lang.String> stopCount = new ArrayList<>();
    private java.util.List<java.lang.String> stopInterval = new ArrayList<>();
    private java.util.List<java.lang.String> ruleName = new ArrayList<>();
    private java.util.List<java.lang.String> preInfo = new ArrayList<>();
    private java.util.List<java.lang.String> postInfo = new ArrayList<>();
    private java.util.List<java.lang.String> condCount = new ArrayList<>();
    private java.util.List<java.lang.String> condTerm = new ArrayList<>();
    private java.util.List<java.lang.String> condGroup1 = new ArrayList<>();
    private java.util.List<java.lang.String> condPriority1 = new ArrayList<>();
    private java.util.List<java.lang.String> condGroup2 = new ArrayList<>();
    private java.util.List<java.lang.String> condPriority2 = new ArrayList<>();


    public OaseActionUtility() {
    }

    public java.util.List<java.lang.String> getId() {
        return this.id;
    }

    public void setId(java.util.List<java.lang.String> id) {
        this.id = id;
    }

    public java.util.List<java.lang.String> getParameterInfo() {
        return this.parameterInfo;
    }

    public void setParameterInfo(java.util.List<java.lang.String> parameterInfo) {
        this.parameterInfo = parameterInfo;
    }

    public java.util.List<java.lang.String> getRetryCount() {
        return this.retryCount;
    }

    public void setRetryCount(java.util.List<java.lang.String> retryCount) {
        this.retryCount = retryCount;
    }

    public java.util.List<java.lang.String> getRetryInterval() {
        return this.retryInterval;
    }

    public void setRetryInterval(java.util.List<java.lang.String> retryInterval) {
        this.retryInterval = retryInterval;
    }

    public java.util.List<java.lang.String> getStopCount() {
        return this.stopCount;
    }

    public void setStopCount(java.util.List<java.lang.String> stopCount) {
        this.stopCount = stopCount;
    }

    public java.util.List<java.lang.String> getStopInterval() {
        return this.stopInterval;
    }

    public void setStopInterval(java.util.List<java.lang.String> stopInterval) {
        this.stopInterval = stopInterval;
    }

    public java.util.List<java.lang.String> getRuleName() {
        return this.ruleName;
    }

    public void setRuleName(java.util.List<java.lang.String> ruleName) {
        this.ruleName = ruleName;
    }

    public java.util.List<java.lang.String> getPreInfo() {
        return this.preInfo;
    }

    public void setPreInfo(java.util.List<java.lang.String> preInfo) {
        this.preInfo = preInfo;
    }

    public java.util.List<java.lang.String> getPostInfo() {
        return this.postInfo;
    }

    public void setPostInfo(java.util.List<java.lang.String> postInfo) {
        this.postInfo = postInfo;
    }

    public java.util.List<java.lang.String> getCondCount() {
        return this.condCount;
    }

    public void setCondCount(java.util.List<java.lang.String> condCount) {
        this.condCount = condCount;
    }

    public java.util.List<java.lang.String> getCondTerm() {
        return this.condTerm;
    }

    public void setCondTerm(java.util.List<java.lang.String> condTerm) {
        this.condTerm = condTerm;
    }

    public java.util.List<java.lang.String> getCondGroup1() {
        return this.condGroup1;
    }

    public void setCondGroup1(java.util.List<java.lang.String> condGroup1) {
        this.condGroup1 = condGroup1;
    }

    public java.util.List<java.lang.String> getCondPriority1() {
        return this.condPriority1;
    }

    public void setCondPriority1(java.util.List<java.lang.String> condPriority1) {
        this.condPriority1 = condPriority1;
    }

    public java.util.List<java.lang.String> getCondGroup2() {
        return this.condGroup2;
    }

    public void setCondGroup2(java.util.List<java.lang.String> condGroup2) {
        this.condGroup2 = condGroup2;
    }

    public java.util.List<java.lang.String> getCondPriority2() {
        return this.condPriority2;
    }

    public void setCondPriority2(java.util.List<java.lang.String> condPriority2) {
        this.condPriority2 = condPriority2;
    }

    public void addRuleName(String ruleName) {
        this.ruleName.add(ruleName);
    }

    public void addId(String id) {
        this.id.add(id);
    }

    public void addParameterInfo(String parameterInfo) {
        this.parameterInfo.add(parameterInfo);
    }

    public void addRetryInterval(String retryInterval) {
        this.retryInterval.add(retryInterval);
    }

    public void addRetryCount(String retryCount) {
        this.retryCount.add(retryCount);
    }

    public void addStopInterval(String stopInterval) {
        this.stopInterval.add(stopInterval);
    }

    public void addStopCount(String stopCount) {
        this.stopCount.add(stopCount);
    }

    public void addPreInfo(String preInfo) {
        this.preInfo.add(preInfo);
    }

    public void addPostInfo(String postInfo) {
        this.postInfo.add(postInfo);
    }

    public void addCondCount(String condCount) {
        this.condCount.add(condCount);
    }

    public void addCondTerm(String condTerm) {
        this.condTerm.add(condTerm);
    }

    public void addCondGroup1(String condGroup1) {
        this.condGroup1.add(condGroup1);
    }

    public void addCondPriority1(String condPriority1) {
        this.condPriority1.add(condPriority1);
    }

    public void addCondGroup2(String condGroup2) {
        this.condGroup2.add(condGroup2);
    }

    public void addCondPriority2(String condPriority2) {
        this.condPriority2.add(condPriority2);
    }

    public OaseActionUtility(java.util.List<java.lang.String> id,
            java.util.List<java.lang.String> parameterInfo,
            java.util.List<java.lang.String> retryCount,
            java.util.List<java.lang.String> retryInterval,
            java.util.List<java.lang.String> stopCount,
            java.util.List<java.lang.String> stopInterval,
            java.util.List<java.lang.String> ruleName,
            java.util.List<java.lang.String> preInfo,
            java.util.List<java.lang.String> postInfo,
            java.util.List<java.lang.String> condCount,
            java.util.List<java.lang.String> condTerm,
            java.util.List<java.lang.String> condGroup1,
            java.util.List<java.lang.String> condPriority1,
            java.util.List<java.lang.String> condGroup2,
            java.util.List<java.lang.String> condPriority2) {
        this.id = id;
        this.parameterInfo = parameterInfo;
        this.retryCount = retryCount;
        this.retryInterval = retryInterval;
        this.stopCount = stopCount;
        this.stopInterval = stopInterval;
        this.ruleName = ruleName;
        this.preInfo = preInfo;
        this.postInfo = postInfo;
        this.condCount = condCount;
        this.condTerm = condTerm;
        this.condGroup1 = condGroup1;
        this.condPriority1 = condPriority1;
        this.condGroup2 = condGroup2;
        this.condPriority2 = condPriority2;
    }

}