/* Copyright 2019 NEC Corporation

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at
 
     http://www.apache.org/licenses/LICENSE-2.0
 
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

*/
package com.castlezone.mco_collaboration;
import java.util.List;
import java.util.ArrayList;
import java.lang.String;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OaseActionUtility implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    private java.util.List<java.lang.String> id = new ArrayList<>();
    private java.util.List<java.lang.String> parameterInfo = new ArrayList<>();
    private java.util.List<java.lang.String> retryCount = new ArrayList<>();
    private java.util.List<java.lang.String> retryInterval = new ArrayList<>();
    private java.util.List<java.lang.String> stopCount = new ArrayList<>();
    private java.util.List<java.lang.String> stopInterval = new ArrayList<>();
    private java.util.List<java.lang.String> ruleName = new ArrayList<>();
    private java.util.List<java.lang.String> preInfo = new ArrayList<>();


    public OaseActionUtility() {
    }

    public java.util.List<java.lang.String> getId() {
        return this.id;
    }

    public void setId(java.util.List<java.lang.String> id) {
        this.id = id;
    }

    public java.util.List<java.lang.String> getParameterInfo() {
        return this.parameterInfo;
    }

    public void setParameterInfo(java.util.List<java.lang.String> parameterInfo) {
        this.parameterInfo = parameterInfo;
    }

    public java.util.List<java.lang.String> getRetryCount() {
        return this.retryCount;
    }

    public void setRetryCount(java.util.List<java.lang.String> retryCount) {
        this.retryCount = retryCount;
    }

    public java.util.List<java.lang.String> getRetryInterval() {
        return this.retryInterval;
    }

    public void setRetryInterval(java.util.List<java.lang.String> retryInterval) {
        this.retryInterval = retryInterval;
    }

    public java.util.List<java.lang.String> getStopCount() {
        return this.stopCount;
    }

    public void setStopCount(java.util.List<java.lang.String> stopCount) {
        this.stopCount = stopCount;
    }

    public java.util.List<java.lang.String> getStopInterval() {
        return this.stopInterval;
    }

    public void setStopInterval(java.util.List<java.lang.String> stopInterval) {
        this.stopInterval = stopInterval;
    }

    public java.util.List<java.lang.String> getRuleName() {
        return this.ruleName;
    }

    public void setRuleName(java.util.List<java.lang.String> ruleName) {
        this.ruleName = ruleName;
    }

    public java.util.List<java.lang.String> getPreInfo() {
        return this.preInfo;
    }

    public void setPreInfo(java.util.List<java.lang.String> preInfo) {
        this.preInfo = preInfo;
    }

    public void addRuleName(String ruleName) {
        this.ruleName.add(ruleName);
    }

    public void addId(String id) {
        this.id.add(id);
    }

    public void addParameterInfo(String parameterInfo) {
        this.parameterInfo.add(parameterInfo);
    }

    public void addRetryInterval(String retryInterval) {
        this.retryInterval.add(retryInterval);
    }

    public void addRetryCount(String retryCount) {
        this.retryCount.add(retryCount);
    }

    public void addStopInterval(String stopInterval) {
        this.stopInterval.add(stopInterval);
    }

    public void addStopCount(String stopCount) {
        this.stopCount.add(stopCount);
    }

    public void addPreInfo(String preInfo) {
        this.preInfo.add(preInfo);
    }

    public OaseActionUtility(java.util.List<java.lang.String> id,
            java.util.List<java.lang.String> parameterInfo,
            java.util.List<java.lang.String> retryCount,
            java.util.List<java.lang.String> retryInterval,
            java.util.List<java.lang.String> stopCount,
            java.util.List<java.lang.String> stopInterval,
            java.util.List<java.lang.String> ruleName,
            java.util.List<java.lang.String> preInfo) {
        this.id = id;
        this.parameterInfo = parameterInfo;
        this.retryCount = retryCount;
        this.retryInterval = retryInterval;
        this.stopCount = stopCount;
        this.stopInterval = stopInterval;
        this.ruleName = ruleName;
        this.preInfo = preInfo;
    }

}